### ISSUE TITLE
cannot find module './credentials'

### ISSUE THREAD

**Issue by peterennis** [javebratt/crud-firestore-ionic-v4#1]
Windows 10 x64
I created a `credentials.ts` file from the firebase config of my created app.
Commented out <script> tags.
Tried in src and root dir.
A fake example is needed in the README for getting started,
with instructions on where the file should be placed.
![capture368](https://user-images.githubusercontent.com/140737/43937632-a726d4be-9c13-11e8-9afe-6bcbd08deeb5.png)

**Comment by peterennis** [comment]
e.g.
Create the file `credentials.ts`
Place the file in your `\app` folder
The file should contain your firebase configuration information
from the console

e.g.

export const firebaseConfig = {
    apiKey: 'your api key goes here',
    authDomain: 'your authDomain goes here',
    databaseURL: 'your databaseUrl goes here',
    projectId: 'your projectId goes here',
    storageBucket: 'your storageBucket goes here',
    messagingSenderId: 'your messagingSenderId goes here'
  }
};

The current home page, after serving the app, is this:
![capture369](https://user-images.githubusercontent.com/140737/43939041-07638f36-9c1c-11e8-9883-fb9db83be4d4.png)

**Comment by javebratt** [comment]
Hey there, this is the source code example of a blog post I wrote here: https://javebratt.com/crud-ionic-firestore/

The post explains how to create everything, for example, for this, it says:

> Go into your src/app folder and create a file called credentials.ts the idea of this file is to keep all of our credentials in one place, this file shouldn’t be in source control so add it to your .gitignore file.

> Copy your config object to that page. I’m going to change the name to something that makes more sense to me:

```js
export var firebasConfig = {
  apiKey: "AIzaSyBJT6tfre8uh3LGBm5CTiO5DUZ4",
  authDomain: "javebratt-playground.firebaseapp.com",
  databaseURL: "https://javebratt-playground.firebaseio.com",
  projectId: "javebratt-playground",
  storageBucket: "javebratt-playground.appspot.com",
  messagingSenderId: "3676553551"
};
```

**Comment by peterennis** [comment]
This is useful information to add to the missing README for people who want to try the app and
arrive here by a github search, not the blog.
