### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by peterennis** [javebratt/crud-firestore-ionic-v4#2]

**Comment by javebratt** [comment]
What do you mean?

**Comment by peterennis** [comment]
Here:
https://blog.github.com/2013-07-15-choosing-an-open-source-license/

Contribution guidelines here:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

If you don't really care for legalese you could use this :)
http://www.wtfpl.net/about/

The GitHub view:
https://blog.github.com/2015-03-09-open-source-license-usage-on-github-com/

**Comment by peterennis** [comment]
Q: What do you mean?

A: The answer to this:
https://github.com/javebratt/ionic-firebase-mega-starter

```
I still have a lot to figure out in terms of how I'm going to handle this, but it's going to be open source and I'm thinking MIT licenced.

Jorge Vergara @javebratt
```
